# Generated by Django 5.2.8 on 2025-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube video URL', max_length=500, null=True),
        ),
    ]
