# Generated by Django 5.2.8 on 2025-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, help_text='Share a link (any website)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_video',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
