# Generated by Django 5.2.8 on 2025-11-28 14:22

import security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[security.validators.validate_no_sql_injection])),
                ('mission', models.TextField(help_text='Mission statement')),
                ('vision', models.TextField(help_text='Vision statement')),
                ('history', models.TextField(blank=True, help_text='Organization history')),
                ('description', models.TextField(help_text='General description')),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('working_hours', models.TextField(help_text='e.g., Mon-Fri: 8:00 AM - 4:30 PM')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[security.validators.validate_no_sql_injection])),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('published_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Announcement expires after this date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[security.validators.validate_no_sql_injection])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('appointment', 'Appointment Request'), ('service', 'Service Information'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('emergency', 'Emergency'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField(validators=[security.validators.validate_no_sql_injection])),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[security.validators.validate_no_sql_injection])),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Google Maps latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Google Maps longitude coordinate', max_digits=9)),
                ('working_hours', models.TextField()),
                ('is_main_office', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Additional location details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
            ],
            options={
                'ordering': ['-is_main_office', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[security.validators.validate_no_sql_injection])),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-heartbeat', help_text='FontAwesome icon class (e.g., fa-heartbeat, fa-syringe)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('details', models.TextField(blank=True, help_text='Extended service details')),
                ('requirements', models.TextField(blank=True, help_text='What patients need to bring')),
                ('schedule', models.CharField(blank=True, help_text='Service availability schedule', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[security.validators.validate_no_sql_injection])),
                ('position', models.CharField(choices=[('director', 'Director'), ('deputy_director', 'Deputy Director'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('dentist', 'Dentist'), ('admin', 'Administrative Staff'), ('technician', 'Medical Technician'), ('other', 'Other')], max_length=50)),
                ('custom_position', models.CharField(blank=True, help_text='Use this for positions not in the list', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField(blank=True, help_text='Education and certifications')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
