# Generated by Django 5.2.8 on 2025-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='Paste the complete Google Maps embed URL from iframe src (e.g., https://www.google.com/maps/embed?pb=...)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Google Maps latitude coordinate (optional if using embed_map_url)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Google Maps longitude coordinate (optional if using embed_map_url)', max_digits=9, null=True),
        ),
    ]
