# Generated by Django 5.2.8 on 2025-11-28 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0002_location_google_maps_embed_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='google_maps_embed',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Google Maps latitude coordinate', max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Google Maps longitude coordinate', max_digits=9),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
