# Generated by Django 5.2.8 on 2025-11-28 20:03

import django.db.models.deletion
import security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0004_position_and_migrate_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[security.validators.validate_no_sql_injection])),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', models.TextField(help_text='Brief description of the activity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('activity_date', models.DateField(help_text='Date of the activity')),
                ('activity_time', models.CharField(blank=True, help_text='e.g., 9:00 AM - 3:00 PM', max_length=100)),
                ('custom_location', models.CharField(blank=True, help_text='Custom location if not in Location list', max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants (leave empty for unlimited)', null=True)),
                ('is_registration_required', models.BooleanField(default=False, help_text='Whether registration is required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='Activity location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='healthcenter.location')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date', 'title'],
            },
        ),
    ]
