# Generated by Django 5.2.8 on 2025-11-28 20:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Brief description of the activity', verbose_name='Description'),
        ),
    ]
