# Generated by Django 5.2.8 on 2025-11-28 20:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0006_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='General description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Organization history', verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Mission statement', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Vision statement', verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='about',
            name='working_hours',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='e.g., Mon-Fri: 8:00 AM - 4:30 PM', verbose_name='Working Hours'),
        ),
    ]
