# Generated by Django 5.2.8 on 2025-11-28 20:30

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0007_alter_about_address_alter_about_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Extended service details', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='service',
            name='requirements',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='What patients need to bring', verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid "slug" consisting of letters, numbers, underscores or hyphens.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='qualifications',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Education and certifications', verbose_name='Qualifications'),
        ),
    ]
