# Generated by Django 5.2.8 on 2025-11-28 21:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0008_alter_announcement_content_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Education and certifications'),
        ),
    ]
